# Usar la imagen oficial de NGINX como base
FROM nginx:latest

# Copiar el archivo HTML al directorio de contenido estático de NGINX
COPY index.html /usr/share/nginx/html

# Exponer el puerto 80 para que NGINX sea accesible desde fuera del contenedor
EXPOSE 80
